# permissions for end users to edit awsvmschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: awsvmscheduler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vm-scheduler-operator
    app.kubernetes.io/part-of: vm-scheduler-operator
    app.kubernetes.io/managed-by: kustomize
  name: awsvmscheduler-editor-role
rules:
- apiGroups:
  - aws.persistent.com
  resources:
  - awsvmschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.persistent.com
  resources:
  - awsvmschedulers/status
  verbs:
  - get
