---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulers/finalizers
  verbs:
  - update
- apiGroups:
  - aws.xyzcompany.com
  resources:
  - awsvmschedulers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulers/finalizers
  verbs:
  - update
- apiGroups:
  - azure.xyzcompany.com
  resources:
  - azurevmschedulers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulers/finalizers
  verbs:
  - update
- apiGroups:
  - gcp.xyzcompany.com
  resources:
  - gcpvmschedulers/status
  verbs:
  - get
  - patch
  - update
